branch-defaults:
  master:
    environment: mateusguerracom-prod
environment-defaults:
  mateusguerracom-prod:
    branch: null
    repository: null
global:
  application_name: mateusguerra.com
  branch: null
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:sa-east-1::platform/Docker running on
    64bit Amazon Linux/2.8.4
  default_region: sa-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
